#!/usr/bin/env python3
"""
Columbia River DART Scraper
============================
Downloads water temperature (River Environment) and adult fish passage
data from Columbia Basin Research's DART system (cbr.washington.edu/dart).

DART's report generator (mg.php) is meant to be called programmatically —
the site documents "a method to generate a link for querying results
directly from programming scripts and other automated processes."
See: https://www.cbr.washington.edu/dart/overview

PARAMETER SCHEME
----------------
Both query schemes below were read off DART's own query forms
(/dart/query/river_graph_text and /dart/query/adult_graph_text) and
verified against live responses.

Two things about those forms are easy to get wrong, and both are handled
here so callers can use readable names:

  * The river form DISPLAYS "Temperature (WQM)" but SUBMITS "Temp (WQM)".
    Several parameters differ this way; RIVER_PARAMS maps label -> value.
  * The adult form carries species in its own `ftype[]` field, as short
    codes ("Chinook" -> "fc"), NOT in `data[]`. On the adult form `data[]`
    selects optional 10-year-average overlays and is left empty here.
    SPECIES_CODES maps name -> code.

If a query still returns nothing useful, the safest fix is:
  1. Go to https://www.cbr.washington.edu/dart/query/river_graph_text
     (or .../adult_graph_text for fish passage)
  2. Make your selections (year, site/dam, species or parameter, dates)
  3. Check "Generate Query Result Link Only" next to Submit Query, and submit
  4. Copy the resulting URL and run this script's `url` mode with it

Usage examples
--------------
  # Water temperature at Bonneville and McNary, 2023-2024
  python dart_scraper.py temperature --locations BON MCN --years 2023 2024 \\
      --parameter "Temperature (WQM)" --out temps.csv
  # (parameter accepts either the form's label or its submit value)

  # Adult Chinook and Steelhead passage at Bonneville, 2024
  python dart_scraper.py passage --projects BON --species Chinook Steelhead \\
      --years 2024 --out passage.csv

  # Use a link you generated by hand on the DART website
  python dart_scraper.py url --url "https://www.cbr.washington.edu/dart/cs/php/rpt/mg.php?...".
"""

import argparse
import io
import time

import pandas as pd
import requests

BASE_URL = "https://www.cbr.washington.edu/dart/cs/php/rpt/mg.php"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (compatible; dart-data-fetcher/1.0; "
                  "for research use of the public DART query API)"
}

# Adult-passage species. DART's adult form submits these as `ftype[]` codes.
SPECIES_CODES = {
    "Chinook": "fc",
    "Jack-Chinook": "fcj",
    "Coho": "fk",
    "Jack-Coho": "fkj",
    "Sockeye": "fb",
    "Steelhead": "fs",
    "Steelhead-Wild": "fsw",
    "Bull Trout": "ft",
    "Lamprey (daytime)": "fl",
    "Lamprey Nighttime": "flnt",
    "Lamprey LPS": "flps",
    "Shad": "fa",
    "Chum": "fe",
    "Pink": "fp",
}

# River Environment parameters whose displayed label differs from the value
# the form actually submits. Labels not listed here submit as themselves.
RIVER_PARAMS = {
    "Temperature (WQM)": "Temp (WQM)",
    "Temperature (Scroll Case)": "Temp (Scroll Case)",
    "Temperature (WQM) 10 Year Avg": "Temp (WQM) 10YrAvg",
    "Temperature (SC) 10 Year Avg": "Temp (SC) 10YrAvg",
}


def resolve_species(name: str) -> str:
    """Map a species name to its DART `ftype[]` code; pass codes through."""
    if name in SPECIES_CODES:
        return SPECIES_CODES[name]
    if name in SPECIES_CODES.values():
        return name
    raise ValueError(
        f"Unknown species {name!r}. Known: {', '.join(sorted(SPECIES_CODES))}"
    )


def resolve_river_parameter(parameter: str) -> str:
    """Map a River Environment label to the value the form submits."""
    return RIVER_PARAMS.get(parameter, parameter)


def fetch_csv(params, retries=3, delay=2) -> pd.DataFrame:
    """GET the DART report endpoint and parse the CSV response."""
    last_err = None
    for attempt in range(retries):
        try:
            resp = requests.get(BASE_URL, params=params, headers=HEADERS, timeout=30)
            resp.raise_for_status()
            text = resp.text
            if text.strip()[:100].lower().lstrip().startswith("<!doctype") or "<html" in text[:200].lower():
                raise ValueError(
                    "Got an HTML page instead of CSV data. Your parameter "
                    "combination probably didn't match a valid DART query. "
                    "Generate the link by hand on the DART site instead "
                    "(see module docstring) and use `url` mode."
                )
            df = pd.read_csv(io.StringIO(text))
            if df.empty:
                print("Warning: query succeeded but returned zero rows.")
            return df
        except Exception as e:  # noqa: BLE001
            last_err = e
            if attempt < retries - 1:
                time.sleep(delay)
    raise RuntimeError(f"Failed to fetch data after {retries} attempts: {last_err}")


def fetch_river_temperature(locations, years, parameter="Temp (WQM)",
                             start_mmdd=None, end_mmdd=None) -> pd.DataFrame:
    """
    River Environment data (includes water temperature) from DART.

    locations : list[str]   DART site codes, e.g. ["BON", "LWG", "MCN"]
    years     : list[int]
    parameter : str  either the label shown on the DART river form or the
                value it submits -- "Temperature (WQM)" and "Temp (WQM)" both
                work. Also: "Temperature (Scroll Case)", "Dissolved Gas",
                "Dissolved Gas Percent", "Outflow", "Inflow", "Spill",
                "Spill Percent", "Elevation", "Turbidity",
                "Barometric Pressure"
    start_mmdd, end_mmdd : "mm/dd" strings, optional date-range filter
    """
    params = [
        ("internal", "1"),
        ("mgconfig", "river"),
        ("outputFormat", "csvSingle"),
        ("avgyear", "0"),
        ("consolidate", "1"),
        ("zeros", "0"),
        ("grid", "1"),
        ("size", "medium"),
        ("startdate", start_mmdd or ""),
        ("enddate", end_mmdd or ""),
    ]
    params += [("year[]", y) for y in years]
    params += [("loc[]", loc) for loc in locations]
    params.append(("data[]", resolve_river_parameter(parameter)))
    return fetch_csv(params)


def fetch_adult_passage(projects, species, years,
                         start_mmdd=None, end_mmdd=None) -> pd.DataFrame:
    """
    Adult fish passage counts from DART.

    projects : list[str]  dam/site codes, e.g. ["BON", "MCN", "LWG"]
    species  : list[str]  names or DART codes, e.g. ["Chinook", "Steelhead",
               "Coho", "Sockeye", "Jack-Chinook", "Jack-Coho", "Bull Trout",
               "Shad", "Chum", "Pink"]. See SPECIES_CODES.
    years    : list[int]
    start_mmdd, end_mmdd : "mm/dd" strings, optional date-range filter

    Species are sent as `ftype[]` codes. `data[]` is deliberately not sent:
    on the adult form it selects 10-year-average overlays, and sending
    species there makes DART reject the query outright with
    "Invalid submission: Data Query Type".
    """
    params = [
        ("internal", "1"),
        ("mgconfig", "adult"),
        ("outputFormat", "csvSingle"),
        ("avgyear", "0"),
        ("consolidate", "1"),
        ("zeros", "1"),
        ("grid", "1"),
        ("size", "medium"),
        ("startdate", start_mmdd or ""),
        ("enddate", end_mmdd or ""),
    ]
    params += [("year[]", y) for y in years]
    params += [("loc[]", p) for p in projects]
    params += [("ftype[]", resolve_species(s)) for s in species]
    return fetch_csv(params)


def fetch_from_url(url: str) -> pd.DataFrame:
    """
    Fetch and parse a URL you generated yourself using DART's "Generate
    Query Result Link Only" option on the website. This is the most
    reliable way to get an exact combination of filters right.
    """
    resp = requests.get(url, headers=HEADERS, timeout=30)
    resp.raise_for_status()
    return pd.read_csv(io.StringIO(resp.text))


def main():
    ap = argparse.ArgumentParser(
        description="Scrape water temperature and adult fish passage data from Columbia River DART"
    )
    sub = ap.add_subparsers(dest="cmd", required=True)

    t = sub.add_parser("temperature", help="Fetch river/water temperature data")
    t.add_argument("--locations", nargs="+", required=True, help="DART site codes, e.g. BON LWG MCN")
    t.add_argument("--years", nargs="+", type=int, required=True)
    t.add_argument("--parameter", default="Temperature (WQM)")
    t.add_argument("--start", default=None, help="mm/dd")
    t.add_argument("--end", default=None, help="mm/dd")
    t.add_argument("--out", default="dart_temperature.csv")

    f = sub.add_parser("passage", help="Fetch adult fish passage counts")
    f.add_argument("--projects", nargs="+", required=True, help="Dam codes, e.g. BON MCN LWG")
    f.add_argument("--species", nargs="+", required=True,
                   help="names or DART codes, e.g. Chinook Steelhead Coho Sockeye")
    f.add_argument("--years", nargs="+", type=int, required=True)
    f.add_argument("--start", default=None, help="mm/dd")
    f.add_argument("--end", default=None, help="mm/dd")
    f.add_argument("--out", default="dart_passage.csv")

    u = sub.add_parser("url", help="Fetch data from a DART-generated query link")
    u.add_argument("--url", required=True)
    u.add_argument("--out", default="dart_data.csv")

    args = ap.parse_args()

    if args.cmd == "temperature":
        df = fetch_river_temperature(args.locations, args.years, args.parameter, args.start, args.end)
    elif args.cmd == "passage":
        df = fetch_adult_passage(args.projects, args.species, args.years, args.start, args.end)
    else:  # url
        df = fetch_from_url(args.url)

    df.to_csv(args.out, index=False)
    print(f"Saved {len(df)} rows to {args.out}")
    print(df.head())


if __name__ == "__main__":
    main()
